### ISSUE TITLE
Deprecated time units in Elixir v1.8.0

### ISSUE THREAD

**Issue by ericentin** [linjunpop/receipt_verifier#10]
This warning is printed during use on Elixir v1.8.0:

```
warning: deprecated time unit: :milliseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
```

Looks like there's two places the code needs to be updated: https://github.com/linjunpop/receipt_verifier/blob/cc89c9bf9d31c61dd643f4d5036b6c8f9989c113/lib/receipt_verifier/receipt/app_receipt.ex#L93 and https://github.com/linjunpop/receipt_verifier/blob/cc89c9bf9d31c61dd643f4d5036b6c8f9989c113/lib/receipt_verifier/receipt/iap_receipt.ex#L98

Since you have already specified Elixir v1.4+, you should not run into any backwards compatibility issues with just changing those to `:millisecond`.

Thanks for your work!

**Comment by linjunpop** [comment]
Thanks, @ericentin, Version 0.13.1 (https://hex.pm/packages/receipt_verifier/0.13.1) is released with this fix. 🍻
