### ISSUE TITLE
No function clause matching parse_response

### ISSUE THREAD

**Issue by dpekar** [linjunpop/receipt_verifier#3]
Hi there - after submitting a base64 encoded receipt string through your package, I get the following error.

```** (FunctionClauseError) no function clause matching in ReceiptVerifier.Parser.parse_response/1```

A response does come back which properly identifies the IAP i was trying to verify by **original_transaction_id**, **original_purchase_date** and several other fields.  The **status** returns 0.

However, looking at the function clauses in parser.ex, it looks like the two fields that are missing from the response I get back are: **latest_receipt** & **receipt**

I have tried adding our shared secret, but get the same result.  Any idea what might be the issue?

Thanks so much for the package!

**Comment by linjunpop** [comment]
@dpekar Did you use the `iOS 7 Style app receipt` which is currently supported.

**Comment by dpekar** [comment]
Hey @linjunpop - thanks for the response!

I thought I was using iOS 7 style, but now I realized I'm not sure how to confirm that is the case.  Is there an easy way to check?

Looking at the response one more time, I'm realizing it would match the pattern below, but it's missing **environment**.  

```  def parse_response(%{"status" => 0, "environment" => environment, "receipt" => receipt})```

I'm definitely getting valid returns back for **status** & **receipt**.

**Comment by linjunpop** [comment]
I think this may be a bug introduced by 342ab28673ec5fbf3127f4687f38e42f89d9a68a, In my test fixtures, the `Sandbox` receipt always returns with an `environment => sandbox`. I will test a production receipt later this day.

**Comment by dpekar** [comment]
Awesome.  Will look for an update from you later.  Thanks!

**Comment by linjunpop** [comment]
I had tried these:

- TestFlight receipt does have `environment: "Sandbox"`
- Production receipt does have `environment: "Production"`

I have no clues why the "environment" key is missing. 😕 

Would you mind provide your receipt or more detailed response? Thanks.

**Comment by dpekar** [comment]
Hey @linjunpop - I started messing around in your project and finally realized that it's set up to verify app receipts and not directly verify in app purchases.  

Very sorry for not realizing this earlier and wasting your time on this! I was able to adapt something that works for my purposes.

Very nice work on the package though :) and thanks again!

**Comment by linjunpop** [comment]
Ah @dpekar, Yes, currently the `iOS 7 Style app receipt` is supported, I have no scenario to use the old IAP transaction receipt, so I did not implement it.
