### ISSUE TITLE
TLS Error

### ISSUE THREAD

**Issue by gordoneliel** [linjunpop/receipt_verifier#8]
Getting this error when verifying a receipt in sanbox:

{_, data} = ReceiptVerifier.verify(attrs["receipt-data"], env: :sandbox)

Got: 

{:error,
 {:failed_connect,
  [
    {:to_address, {'sandbox.itunes.apple.com', 443}},
    {:inet, [:inet], {:tls_alert, 'handshake failure'}}
  ]}}

Terminal: 
['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'hello', 32, 'received SERVER ALERT: Fatal - Handshake Failure', 10]

**Comment by linjunpop** [comment]
I can reproduce this error. I will spend some time investigating it.

**Comment by linjunpop** [comment]
It should be fixed with 3c43c099126e7c8419469bfbe4aa31b7e17d9082

**Comment by linjunpop** [comment]
@gordoneliel https://hex.pm/packages/receipt_verifier/0.13.0 should fix this issue. Feel free to reopen if it's not resolved.
